### ISSUE TITLE
Doesn't emit `require` or `requireFail` events

### ISSUE THREAD

**Issue by phated** [tkellen/js-rechoir#17]
`Liftoff` expects the requiring of a language module to emit an event, either `require` or `requireFail`, when a language file is loaded.  In trying to switch the logic over to `rechoir`, I found that there isn't a way to hook it into this behavior of `liftoff`.  @tkellen any thoughts on how to solve this?

**Comment by silkentrance** [comment]
I think that these events are meant to be captured by the app that uses liftoff.

As such, I believe that it would be better that liftoff utilizes rechoir directly instead of issuing these events, making them altogether obsolete. And it would also be far more efficient instead of issuing the event, waiting for the listener to register the required languages and then call once again for loading the file.

So, wherever liftoff now issues the `require` event, it would instead simply call `rechoir.registerFor()` and then try to require the file in question, ultimately failing with an exception.

**Comment by phated** [comment]
@silkentrance the way gulp uses the events is to log when the transpiler is loaded or failed to load.  I don't think those can be removed.

**Comment by silkentrance** [comment]
Hm, in index.js liftoff refers to this.extensions. I can't find where this is being declared. Could it be that this is a placeholder for node-interpret? If so, the whole shebang should be refactored so that it uses rechoir instead, or am I wrong? Or is this something being passed by the caller and then merged into the this object?

Regardless, if gulp needs the event to be emitted, so be it. Still, liftoff should be using rechoir directly and rechoir should not need to implement the event emitter interface.

**Comment by silkentrance** [comment]
@phated How about something similar to this?

```js
Liftoff.prototype.requireLocal = function (module, basedir) {
  try {
    rechoir.registerFor(module, basedir);
    var result = require(resolve.sync(module, {basedir: basedir}));
    this.emit('require', module, result);
    return result;
  } catch (e) {
    this.emit('requireFail', module, e);
  }
};
```

**Comment by phated** [comment]
that doesn't work with the extra `requires` option

**Comment by silkentrance** [comment]
Huh? I am having a hard time now finding that extra option in both the code and the readme...

**Comment by phated** [comment]
https://github.com/tkellen/node-liftoff/blob/master/index.js#L36-L42 and https://github.com/tkellen/node-liftoff/blob/master/index.js#L114-L125  making your change causes 2 tests to fail

**Comment by silkentrance** [comment]
Ah, looking at the readme it reads

```
opts.extensions

Set extensions to include when searching for a configuration file. If an external module is needed to load a given extension (e.g. .coffee), the module name should be specified as the value for the key.

Type: Object
Default: {".js":null,".json":null}

Examples:

In this example Liftoff will look for myappfile{.js,.json,.coffee}. If a config with the extension .coffee is found, Liftoff will try to require coffee-script/require from the current working directory.

const MyApp = new Liftoff({
  name: 'myapp'
  extensions: {
    '.js': null,
    '.json': null,
    '.coffee': 'coffee-script/register'
  }
});
```

This seems to be obsolete by now with node-interpret being in place.

**Comment by silkentrance** [comment]
@phated well, yes, then we might have two different code paths, one for the opts.require and one for the provable configuration file.

**Comment by phated** [comment]
@silkentrance `registerFor` does the requiring internally, that's why we are unable to do the pattern you suggested.  It also doesn't return the module or path, so there is nothing to emit.

**Comment by phated** [comment]
It's not about code paths, it is about missing functionality.

**Comment by silkentrance** [comment]
@phated I get your point, but consider:

opts.require will cause events to be emitted because liftoff will require those modules in requireLocal.

the configuration file is a different thing, and please forget that proposal for extending the requireLocal function for the time being, as it will instruct rechoir to first registerFor(config) and then result = require(resolve(config)), emitting the resulting module.

See https://github.com/tkellen/node-liftoff/blob/master/index.js#L113-L116

**Comment by phated** [comment]
Currently, gulp logs when `coffee-script/register` is loaded or if it can't load it.  This helps a ton with debugging and this is not supported when switching to any of your suggestions.

**Comment by silkentrance** [comment]
So, perhaps, registerFor returning a tuple consisting of the (extension, moduleName, module) would do the trick for grunt?

Or rather taking an optional callback as a parameter which will then take that above tuple as its argument?

**Comment by phated** [comment]
yeah, something like that would need to be implemented.  none of them seem like a clean API.  would like to hear from @tkellen too

**Comment by silkentrance** [comment]
@phated do you use gitter?

**Comment by tkellen** [comment]
Sorry for the delay in reply on this guys.  I'll see if I can come up with a palatable solution tomorrow.

**Comment by pspeter3** [comment]
This seems pretty useful for the gulpfile logging. Is there anything that can be done to help?

**Comment by silkentrance** [comment]
Personally, I think that with rechoir in place

- the require option is obsolete
- the events require/requireFail should be emulated by https://github.com/tkellen/node-rechoir/issues/17#issuecomment-70347382

in order to make this work.

**Comment by phated** [comment]
After talking this over with @tkellen, we both seem to think that it shouldn't be functionality introduced into rechoir since it is liftoff specific.  That also means that liftoff won't be depending on rechoir and will need to independently implement the new features that were added to rechoir.  It feels bad to be duplicating logic, but they are different enough to warrant it and still keep rechoir a clean API.

**Comment by silkentrance** [comment]
Silly me, but this deems to be silly to me... But I guess that you both guys know what you are doing. node-interpret-for-liftoff along the way, anyone?

I am currently working on a patch for liftoff that will enable just this, including reuse of node-rechoir.

**Comment by phated** [comment]
I'd be interested in seeing the patch for liftoff, but I see no way to do it.  Let's leave this open until there is code to determine if it will work.  Thanks for the hard work @silkentrance

**Comment by tkellen** [comment]
I'm changing this so that when rechoir fails, it throws an error which includes an array of errors for all possible fallbacks. Liftoff can emit errors for each one. Also, I'm removing the direct dependency on `interpret`. @silkentrance, this will allow you to provide whatever config you want.  

See https://github.com/tkellen/js-rechoir/tree/0.5.0

**Comment by silkentrance** [comment]
@phated, @tkellen: long time since I looked into this. thanks for the ping. When I find the time, I will look into this again this weekend.
